name: Ceneco Advisory Notifier

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  CheckAdvisory:
    environment: email
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Check Advisory
        uses: ./advisory-checker
        id: check-advisory
        with:
          place: ${{ secrets.PLACE }}
      - name: Send text message
        if: steps.check-advisory.outputs.isSendEmail == 'true'
        uses: ./send-sms
        with:
          numbers: ${{ secrets.NUMBERS }}
          place: ${{ secrets.PLACE }}
          time: ${{ steps.check-advisory.outputs.dateAndTime }}
          api: ${{ secrets.SMSAPI }}
